module.exports = {
  state : {
    ECA_NORMAL : 1,
    ECA_TIMEOUT : 80,
    ECA_IODONE : 339,
    ECA_ISATTACHED : 424,
    OP_CONN_UP : 6,
    OP_CONN_DOWN : 7,
    CS_NEVER_CONN : 0,
    CS_PREV_CONN: 1,
    CS_CONN: 2,
    CS_CLOSED: 3,
    CS_NEVER_SEARCH : 4
  },
  mask : {
    DBE_VALUE : 1,
    DBE_LOG : 2,
    DBE_ALARM : 4,
    DBE_PROPERTY : 8
  },
  dbr : {
    STRING : 0, 
    INT    : 1, 
    SHORT  : 1, 
    FLOAT  : 2, 
    ENUM   : 3, 
    CHAR   : 4, 
    LONG   : 5, 
    DOUBLE : 6, 
    TIME_STRING  : 14,
    TIME_INT     : 15,
    TIME_SHORT   : 15,
    TIME_FLOAT   : 16,
    TIME_ENUM    : 17,
    TIME_CHAR    : 18,
    TIME_LONG    : 19,
    TIME_DOUBLE  : 20,
    CTRL_STRING  : 28,
    CTRL_INT     : 29,
    CTRL_SHORT   : 29,
    CTRL_FLOAT   : 30,
    CTRL_ENUM    : 31,
    CTRL_CHAR    : 32,
    CTRL_LONG    : 33,
    CTRL_DOUBLE  : 34,
  },
  nativeType : {
    0 : 'CString',
    1 : 'int',
    2 : 'float',
    3 : 'int',
    4 : 'char',
    5 : 'int',
    6 : 'double'
  }
}
